### PR TITLE
Add bootstrapping for plugins that use zeek-config

### PR DESCRIPTION
**Pull request by Neverlord**
Companion PR for https://github.com/zeek/zeek/pull/2954.

### CODE REVIEW

**Comment by ckreibich** [comment]
Dominik I have a basic question — in the current configure scripts (sitting in existing packages & plugins), when configuring based on `zeek-config` output, we have all these ancient variables that pass the corresponding values into cmake: `BRO_CONFIG_PREFIX`, `BRO_CONFIG_INCLUDE_DIR`, etc. The old cmake code expected these, and processed them accordingly. Your approach is to ignore all of this, and under the hood work with information that's effectively identical to getting `zeek-config` outputs — is that correct?

If so, some good tests would be to install Zeek distributions configured with unusual paths (for example for `--plugin_dir` or `--with-broker=...`) and then see whether plugins build/install correctly.

I also really like that approach, if I'm understanding it right — it's great to see the old cruft removed — the only danger I see is that people customized their configure scripts to do unusual things with the old variables, and by ignoring these things now break. I think the odds of that are quite low since people won't normally have had a need to go near that stuff.

**Comment by Neverlord** [comment]
> Your approach is to ignore all of this, and under the hood work with information that's effectively identical to getting `zeek-config` outputs — is that correct?

Yes, pretty much. All that the plugins really need to do is to tell CMake where it can find `ZeekPlugin.cmake`. From here, we are in CMake land and we can use the Zeek package and other config files. We've generated `zeek-config` in the first place, so it can't tell us anything we don't already know.

We also don't really need `BROKER_ROOT_DIR`. I've used it for now since it's there, but we can do without it by storing the Broker path in the bootstrap file as well. My thought was that we aren't going to change all the plugins out there anytime soon, so I left that for a later refinement. Eventually, I'd like to get rid of either `ZeekPluginBootstrap.cmake` or `ZeekPluginConfig.cmake`. Having two separate ways to do something makes things more complicated than they ought to be and it's just asking for trouble in the long run.

> If so, some good tests would be to install Zeek distributions configured with unusual paths (for example for `--plugin_dir` or `--with-broker=...`) and then see whether plugins build/install correctly.

What really hit me this time is that we don't have an automated test for any of this in our CI. This means we can't really make changes/improvements to this setup and confidently merge them if CI passes without doing manual testing on top. And I just didn't know about some of the details, so I couldn't test it. I've relied on CI plus OBS to cover the supported use cases.

Zeek already has lots of plugin tests in its `btest` suite and I've seen Arne adding more recently. All of this testing is already quite awesome. I think all we need is a couple extra tests on top that exercise the plugin machinery on an install prefix. Happy to volunteer for adding those, but ideally I'd need someone with more domain knowledge that can tell me all the dirty details we need to watch out for. 🙂

**Comment by ckreibich** [comment]
> We've generated zeek-config in the first place, so it can't tell us anything we don't already know.

Yes, exactly!

> What really hit me this time is that we don't have an automated test for any of this in our CI.

Almost, yeah. There are the Zeek-level plugin tests, as you mention. The zkg package template only recently gained CI support, but it already covers basic plugins, Spicy, and (with zeek/package-template#17) BiFs. Tim suggested we add a BinPAC scenario there, which is a good point. Neither of these cover unusually-configured Zeek installations.

One biggie to remember is that we have two scenarios for working with plugins: the `init-plugin` [skeleton](https://github.com/zeek/zeek-aux/tree/master/plugin-support) (which Zeek's tests use), and the plugin feature in the zkg [package template](https://github.com/zeek/package-template/tree/master/features/plugin). Each has its place though most people only encounter the latter. Arne also recently argued that we should check some popular packages as part of CI, to cover stuff that's "out there".

I'll tinker a bit and will follow up, but I think we're very close now. Thanks for working on this right away.

**Comment by ckreibich** [comment]
I've tried a few things and learned a lot. Unfortunately it's not all good news yet.

I can confirm that Community ID installs on a default Zeek install (`./configure --prefix=...`, no other tweaks), which indicates that BiFs work — great! But when I use a package that uses binpac, it fails. I tried [`cisagov/icsnpp-bacnet`](https://github.com/cisagov/icsnpp-bacnet) from a local clone, via `zkg install .` This works with Zeek 5.2, but with your latest code I get:
```
CMake Warning at /home/christian/inst/opt/zeek/share/zeek/cmake/ZeekPlugin.cmake:121 (message):
  Package requires CMake 3.0 which is less than Zeek's requirement (3.15.0).
  This will likely cause build failures and should be fixed.
Call Stack (most recent call first):
  CMakeLists.txt:5 (include)


CMake Warning (dev) at /home/christian/inst/opt/zeek/share/zeek/cmake/ZeekPlugin.cmake:100 (if):
  Policy CMP0057 is not set: Support new IN_LIST if() operator.  Run "cmake
  --help-policy CMP0057" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  IN_LIST will be interpreted as an operator when the policy is set to NEW.
  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  /home/christian/inst/opt/zeek/share/zeek/cmake/ZeekPluginDynamic.cmake:66 (zeek_next_pac_block)
  /home/christian/inst/opt/zeek/share/zeek/cmake/ZeekPlugin.cmake:167 (zeek_add_dynamic_plugin)
  /home/christian/inst/opt/zeek/share/zeek/cmake/ZeekPluginCommon.cmake:70 (zeek_add_plugin)
  CMakeLists.txt:12 (zeek_plugin_end)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at /home/christian/inst/opt/zeek/share/zeek/cmake/ZeekPlugin.cmake:100 (if):
  if given arguments:

    "arg" "IN_LIST" "separators"

  Unknown arguments specified
Call Stack (most recent call first):
  /home/christian/inst/opt/zeek/share/zeek/cmake/ZeekPluginDynamic.cmake:66 (zeek_next_pac_block)
  /home/christian/inst/opt/zeek/share/zeek/cmake/ZeekPlugin.cmake:167 (zeek_add_dynamic_plugin)
  /home/christian/inst/opt/zeek/share/zeek/cmake/ZeekPluginCommon.cmake:70 (zeek_add_plugin)
  CMakeLists.txt:12 (zeek_plugin_end)
```
Could you give that a go to see if you're hitting this too?

I also learned that using customized Zeek builds is pretty messy. I hit many problems, including in the Zeek 5.2 branch (so independently of your changes!). This isn't super surprising since we rarely apply these tweaks. For example:
- With Zeek 5.2, when I use a separately built `bifcl` and configure with `--with-bifcl`, it shows correctly in the configure output and doesn't get installed, but you cannot actually learn that fact via `zeek-config` — it doesn't have an option to tell you. Plugin installs blow up because they cannot find `bifcl`. I have yet to try this with your latest branch.
- With Zeek 5.2, when I use a separately built binpac, it shows correctly in configure but Zeek still builds and installs it — and, `zeek-config --binpac_root` shows the Zeek tree, not the `binpac` I provided. (There's also a discrepancy between providing a binpac executable to configure, but `zeek-config` reporting an installation toplevel dir, per `--binpac_root`). Here too I have yet to try with your branch.
- With Zeek 5.2, I can tweak `--libdir` and `--plugindir` at configure time, install the whole thing, and then install Community ID okay, but when I use your branch I encounter the following:
```
CMake Error at /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:76 (find_package):
  Could not find a package configuration file provided by "Broker" with any
  of the following names:

    BrokerConfig.cmake
    broker-config.cmake

  Add the installation prefix of "Broker" to CMAKE_PREFIX_PATH or set
  "Broker_DIR" to a directory containing one of the above files.  If "Broker"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /home/christian/inst/opt/zeek/share/zeek/cmake/ZeekConfig.cmake:51 (find_dependency)
  /home/christian/inst/opt/zeek/share/zeek/cmake/ZeekPlugin.cmake:27 (find_package)
  /home/christian/inst/opt/zeek/share/zeek/cmake/ZeekPlugin.cmake:50 (zeek_plugin_bootstrapping)
  CMakeLists.txt:22 (include)
```
If we try to straighten this all out now, I think we risk bikeshedding the whole thing into a whole bunch more configure/cmake tweaks. I suggest we table this for now and iterate via future PRs, and focus on getting common packages to install on a standard (non-customized) Zeek install.

One more thing: I noticed that looks suspicious: since the recent cmake merge, a plain `configure` reports
```
BinPAC:            /home/christian/devel/zeek/zeek/build/auxil/binpac/src/binpac
```
(i.e., it reports a place in my build tree) whereas for Zeek 5.2 it says
```
BinPAC:            included
```
The latter seems nicer.

**Comment by timwoj** [comment]
> This works with Zeek 5.2, but with your latest code I get:

See this comment and the ones below it: https://github.com/zeek/zeek/pull/2799#issuecomment-1504305935. It was a conscious design to not try to fix this, and to instead warn on plugins that haven't updated to a newer version of CMake in a long time.

**Comment by ckreibich** [comment]
I bumped the cmake requirement in `cisagov/icsnpp-bacnet` to Zeek's 3.15 and am now seeing the following (this branch and a plain `configure --prefix=...` install):
```
$ ./configure
...
-- Found BinPAC: /home/christian/inst/opt/zeek/include/binpac
```
So a folder, not the executable. This blows up in the subsequent binpac invocation:
```
$ make
...
[ 20%] [BINPAC] Processing /home/christian/devel/zeek/packages-cloned/cisagov/icsnpp-bacnet/src/bacnet.pac
make[3]: /home/christian/inst/opt/zeek/include/binpac: Permission denied
```
Looks like the `find_file` in `FindBinPAC.cmake` somehow picks up the wrong thing now.

**Comment by Neverlord** [comment]
With the latest version, I get `icsnpp-bacnet` to compile now (after patching the minimum required CMake version).

**Comment by timwoj** [comment]
@Neverlord Does that last commit also fix https://github.com/zeek/zeek/issues/2932?

**Comment by Neverlord** [comment]
I've had the same issue with `cisagov/icsnpp-bacnet` and it's building for me know, so it should be fixed.

**Review by awelzel — APPROVED** [review]
Approving.

@Neverlord - should we track any follow-up Christian mentioned [here](https://github.com/zeek/cmake/pull/64#issuecomment-1510730369) in a separate ticket? We could just make the whole comment a new issue :-)

**Comment by dopheide-esnet** [comment]
Coming over here from zeek#2932.   Build is working now, but I tend to agree something is wrong when using zeek is built with --plugindir.  'make install' results in:

Install the project...
-- Install configuration: ""
'/usr/local/zeek/versions/ed169b537cc6e21725f66fd340a7122d84a19cc4/share/zeek/cmake/zeek-plugin-install-package.sh' 'ESnet_Zeek_Exporter' '/'

Which installs the package in / rather than whatever was defined in by plugindir.

**Pull request merged**
